### PR TITLE
Center button contents

### PR DESCRIPTION
**Pull request by Plootie**
Would love both of your input on this @artehe @J0nathan550 I can't tell if centered looks better or not

### CODE REVIEW

**Comment by J0nathan550** [comment]
If icons would be on same position on left and text on center this would look good! 😄

**Comment by Plootie** [comment]
I did try that initially but since they're inside a stack panel a center align wont work so it'd require some kind of change to the buttons

**Comment by J0nathan550** [comment]
> I did try that initially but since they're inside a stack panel a center align wont work so it'd require some kind of change to the buttons

You can use grid :D

**Comment by Plootie** [comment]
Idk if my brain is just cooked tonight but using a grid set to `auto, *` wouldn't center align the text since the content align would be to the column it's in and I can't think of a better way. I'm sure there is one I just can't think of how to do this tonight

**Comment by Plootie** [comment]
I've returned to this and determined with the size constraints there probably isn't a good way to have the icons be left aligned and text center aligned (`size, * , size` would technically work but wouldn't work for the larger texts). Do you think this should be merged or closed?

**Comment by artehe** [comment]
I'd say just close it for now, gonna have some tweaks to that page soon ish anyway I think if I get round to improving the install ui stuffs

**Pull request closed without merging**
