### PR TITLE
Fix server detecting

### PR DESCRIPTION
**Pull request by Plootie**
Remove old irrelevant detection code

### CODE REVIEW

**Comment by Plootie** [comment]
@J0nathan550 Can you give this a try and see if it fixes it? I don't know if this actually is the issue but it's my first assumption and needed removing anyway

**Comment by J0nathan550** [comment]
No doesn't fix issue.

**Review by J0nathan550 — CHANGES_REQUESTED** [review]
Works, but also add ability in ServerViewModelPage ability to cancel while it's initializing the server. Please

**Review by J0nathan550 — APPROVED** [review]
Works now as it should 😄

**Pull request merged**
